# Generated by Django 5.1.7 on 2025-10-22 15:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('HoD', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyRegistrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('signature', models.ImageField(upload_to='registrar_signatures/')),
                ('faculty_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('generated_by', models.CharField(max_length=100)),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('dean_signature', models.BooleanField(default=False)),
                ('registrar_signature', models.BooleanField(default=False)),
                ('vc_signature', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='transcripts/')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('official', 'Official Transcript'), ('unofficial', 'Unofficial Transcript')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(help_text='Enter the WhatsApp group invite link.')),
                ('icon', models.CharField(default='fa-users', help_text="FontAwesome icon class, e.g., 'fa-users'.", max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Group',
                'verbose_name_plural': 'WhatsApp Groups',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('exams_office', 'Exams Office'), ('accounts_office', 'Accounts Office'), ('hod', 'Head of Department'), ('dean_of_student', 'Dean of Student'), ('vice_chancellor', 'Vice Chancellor'), ('registrar', 'Registrar')], max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='staff_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('index_number', models.CharField(max_length=50, unique=True)),
                ('date_entered', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('owes_fees', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.program')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.CharField(max_length=100)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('transcript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='app.transcript')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending Registrar Review'), ('under_review', 'Under Registrar Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_batches', to='app.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_type', models.CharField(blank=True, choices=[('official', 'Official Transcript'), ('unofficial', 'Unofficial Transcript')], max_length=20, null=True)),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference_code', models.CharField(max_length=100, unique=True)),
                ('payment_made', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('selected_faculty_registrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_requests', to='app.facultyregistrar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('disapproved', 'Disapproved'), ('reapproved', 'Re-approved')], max_length=20)),
                ('approved_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('transcript_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='app.transcriptrequest')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddField(
            model_name='transcript',
            name='transcript_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='app.transcriptrequest'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared', models.BooleanField(default=False)),
                ('officer_name', models.CharField(max_length=100)),
                ('date_checked', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transcript_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='app.transcriptrequest')),
            ],
        ),
        migrations.CreateModel(
            name='FeeClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared', models.BooleanField(default=False)),
                ('owes', models.BooleanField(default=False)),
                ('amount_owed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('officer_name', models.CharField(max_length=255)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('date_checked', models.DateTimeField(auto_now_add=True)),
                ('transcript_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_clearance', to='app.transcriptrequest')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('changes_made', models.TextField(blank=True, null=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='app.transcriptbatch')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('pending', 'Pending'), ('cash_office', 'At Cash Office'), ('exams_office', 'At Exams Office'), ('registrar', 'At Registrar'), ('approved', 'Approved'), ('dispatched', 'Dispatched'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='transcript_status_attachments/')),
                ('transcript_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='app.transcriptrequest')),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('date_verified', models.DateTimeField(blank=True, null=True)),
                ('transcript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='app.transcript')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='app.transcriptbatch')),
                ('transcript_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='app.transcriptrequest')),
            ],
            options={
                'unique_together': {('batch', 'transcript_request')},
            },
        ),
    ]
