# Generated by Django 5.2.7 on 2025-10-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='staff_signatures/'),
        ),
    ]
