# Generated by Django 5.2.7 on 2025-10-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_staffprofile_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_accounts_office',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_registrar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_superadmin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='transcript_uploads/'),
        ),
    ]
